title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
<<<<<<< HEAD
theme: jekyll-theme-minimal
=======
theme: jekyll-theme-minima
>>>>>>> f108392db3ca4b0e7676ddea0bc65e92895f0daf
